INSERT INTO CARD VALUES (1,'aligator','alligator')
INSERT INTO CARD VALUES (2,'antylopa','antelope')
INSERT INTO CARD VALUES (3,'badminton','badminton')
INSERT INTO CARD VALUES (5,'baran','ram')
INSERT INTO CARD VALUES (6,'bawół','buffalo')
INSERT INTO CARD VALUES (7,'bejzbol','baseball')
INSERT INTO CARD VALUES (8,'bieganie','running')
INSERT INTO CARD VALUES (9,'bilard','pool, snooker')
INSERT INTO CARD VALUES (10,'bizon','bison')
INSERT INTO CARD VALUES (11,'boks','boxing')
INSERT INTO CARD VALUES (12,'borsuk','badger')
INSERT INTO CARD VALUES (13,'bóbr','beaver')
INSERT INTO CARD VALUES (14,'byk','bull')
INSERT INTO CARD VALUES (15,'chomik','hamster')
INSERT INTO CARD VALUES (16,'ciele','calf')
INSERT INTO CARD VALUES (17,'daniel','fallow deer')
INSERT INTO CARD VALUES (18,'delfin','dolphin')
INSERT INTO CARD VALUES (19,'delfin butlonosy','bottlenose dolphin')
INSERT INTO CARD VALUES (20,'diabeł tasmański','tasmanian devil')
INSERT INTO CARD VALUES (21,'dingo (pies)','dingo dog')
INSERT INTO CARD VALUES (22,'dromader (wielbłąd)','dromedary camel')
INSERT INTO CARD VALUES (23,'dzik','wild boar')
INSERT INTO CARD VALUES (24,'dziobak','platypus')
INSERT INTO CARD VALUES (25,'dżudo','judo')
INSERT INTO CARD VALUES (26,'fenek','fennec fox')
INSERT INTO CARD VALUES (27,'foka','seal')
INSERT INTO CARD VALUES (28,'fretka','ferret')
INSERT INTO CARD VALUES (29,'gazela','gazelle')
INSERT INTO CARD VALUES (30,'gepard','cheetah')
INSERT INTO CARD VALUES (31,'hokej na lodzie','ice hockey')
INSERT INTO CARD VALUES (32,'kajakarstwo','canoeing')
INSERT INTO CARD VALUES (33,'karate','karate')
INSERT INTO CARD VALUES (34,'kolarstwo','cycling')
INSERT INTO CARD VALUES (35,'koszykówka','basketball')
INSERT INTO CARD VALUES (36,'kręgle','bowling')
INSERT INTO CARD VALUES (37,'kręgle','bowling')
INSERT INTO CARD VALUES (38,'łucznictwo','archery')
INSERT INTO CARD VALUES (39,'łyżwiarstwo','skating')
INSERT INTO CARD VALUES (40,'narciarstwo','skiing')
INSERT INTO CARD VALUES (41,'niedźwiedź czarny','black bear')
INSERT INTO CARD VALUES (42,'nosorożec','rhinoceros')
INSERT INTO CARD VALUES (43,'nurkowanie ze sprzętem','scuba-diving')
INSERT INTO CARD VALUES (44,'ocelot','ocelot')
INSERT INTO CARD VALUES (45,'orangutan','orangutan')
INSERT INTO CARD VALUES (46,'orka','orca')
INSERT INTO CARD VALUES (47,'osioł','donkey')
INSERT INTO CARD VALUES (48,'owca','sheep')
INSERT INTO CARD VALUES (49,'pałanka','possum')
INSERT INTO CARD VALUES (50,'pancernik','armadillo')
INSERT INTO CARD VALUES (51,'panda','panda')
INSERT INTO CARD VALUES (52,'panda','giant panda')
INSERT INTO CARD VALUES (53,'pantera','leopard')
INSERT INTO CARD VALUES (54,'pawian','baboon')
INSERT INTO CARD VALUES (55,'pchnięcie kulą','shot put')
INSERT INTO CARD VALUES (56,'pies','dog')
INSERT INTO CARD VALUES (57,'piłka nożna','football')
INSERT INTO CARD VALUES (58,'pływanie','swimming')
INSERT INTO CARD VALUES (59,'prosiak','piglet')
INSERT INTO CARD VALUES (60,'puma','cougar')
INSERT INTO CARD VALUES (61,'renifer','reindeer')
INSERT INTO CARD VALUES (62,'ryś','lynx')
INSERT INTO CARD VALUES (63,'rzutki','darts')
INSERT INTO CARD VALUES (64,'sarna','roe deer')
INSERT INTO CARD VALUES (65,'serwal','serval')
INSERT INTO CARD VALUES (66,'siatkówka','volleyball')
INSERT INTO CARD VALUES (67,'skok w dal','long-jump')
INSERT INTO CARD VALUES (68,'skoki narciarskie','ski jumping')
INSERT INTO CARD VALUES (69,'skunks','skunk')
INSERT INTO CARD VALUES (70,'słoń','elephant')
INSERT INTO CARD VALUES (71,'szczur','rat')
INSERT INTO CARD VALUES (72,'szermierka','fencing')
INSERT INTO CARD VALUES (73,'szop pracz','common raccoon')
INSERT INTO CARD VALUES (74,'szympans','chimpanzee')
INSERT INTO CARD VALUES (75,'szynszyla','chinchilla')
INSERT INTO CARD VALUES (76,'świnia','pig')
INSERT INTO CARD VALUES (77,'świnka morska','guinea pig')
INSERT INTO CARD VALUES (78,'świstak','groundhog')
INSERT INTO CARD VALUES (79,'tchórz','polecat')
INSERT INTO CARD VALUES (80,'tenis stołowy','(ping-pong) table tennis')
INSERT INTO CARD VALUES (81,'tygrys','tiger')
INSERT INTO CARD VALUES (82,'tygrysica','tigress')
INSERT INTO CARD VALUES (83,'nietoperz','bat')
INSERT INTO CARD VALUES (84,'wędkarstwo','fishing')
INSERT INTO CARD VALUES (85,'wielbłąd','camel')
INSERT INTO CARD VALUES (86,'wieloryb','whale')
INSERT INTO CARD VALUES (87,'wiewiórka','squirrel')
INSERT INTO CARD VALUES (88,'wilk','wolf')
INSERT INTO CARD VALUES (89,'windsurfing','windsurfing')
INSERT INTO CARD VALUES (90,'wół','ox')
INSERT INTO CARD VALUES (91,'wspinaczka','climbing')
INSERT INTO CARD VALUES (92,'wydra','otter')
INSERT INTO CARD VALUES (93,'wyścigi','racing')
INSERT INTO CARD VALUES (94,'wyścigi konne','horse racing')
INSERT INTO CARD VALUES (95,'zając hare','hare')
INSERT INTO CARD VALUES (96,'zebra','zebra')
INSERT INTO CARD VALUES (97,'żbik','wildcat')
INSERT INTO CARD VALUES (98,'żyrafa','giraffe')
INSERT INTO CARD VALUES (99,'biurko','desk')
INSERT INTO CARD VALUES (100,'brama','gate')
INSERT INTO CARD VALUES (101,'chodnik','pavement')
INSERT INTO CARD VALUES (102,'dach','roof')
INSERT INTO CARD VALUES (103,'drzwi wejściowe','front door')
INSERT INTO CARD VALUES (104,'dywan','carpet')
INSERT INTO CARD VALUES (105,'firanka','curtain')
INSERT INTO CARD VALUES (106,'fotel','armchair')
INSERT INTO CARD VALUES (107,'garaż','garage')
INSERT INTO CARD VALUES (108,'garnek','pot')
INSERT INTO CARD VALUES (109,'grzejnik','radiator')
INSERT INTO CARD VALUES (110,'jadalnia','dining room')
INSERT INTO CARD VALUES (111,'klucz','key')
INSERT INTO CARD VALUES (112,'kołdra','quilt')
INSERT INTO CARD VALUES (113,'kołdra/koc/itp.','blanket')
INSERT INTO CARD VALUES (114,'komin','chimney')
INSERT INTO CARD VALUES (115,'kominek','fireplace')
INSERT INTO CARD VALUES (116,'komoda','chest of drawers')
INSERT INTO CARD VALUES (117,'kran','tap')
INSERT INTO CARD VALUES (118,'kredens','cupboard')
INSERT INTO CARD VALUES (119,'krzesło','chair')
INSERT INTO CARD VALUES (120,'kuchenka','cooker')
INSERT INTO CARD VALUES (121,'kuchnia','kitchen')
INSERT INTO CARD VALUES (122,'lampka','lamp')
INSERT INTO CARD VALUES (123,'ława','coffee table')
INSERT INTO CARD VALUES (124,'łazienka','bathroom')
INSERT INTO CARD VALUES (125,'lodówka','fridge')
INSERT INTO CARD VALUES (126,'łóżko','bed')
INSERT INTO CARD VALUES (127,'łyżka','spoon')
INSERT INTO CARD VALUES (128,'mikrofalówka','microwave')
INSERT INTO CARD VALUES (129,'miotła','broom')
INSERT INTO CARD VALUES (130,'mydło','soap')
INSERT INTO CARD VALUES (131,'nóż','knife')
INSERT INTO CARD VALUES (132,'obraz','picture')
INSERT INTO CARD VALUES (133,'odkurzacz','vacuum cleaner')
INSERT INTO CARD VALUES (134,'okno','window')
INSERT INTO CARD VALUES (135,'pasta do zębów','toothpaste')
INSERT INTO CARD VALUES (136,'patelnia','pan')
INSERT INTO CARD VALUES (137,'piekarnik','oven')
INSERT INTO CARD VALUES (138,'piwnica','cellar')
INSERT INTO CARD VALUES (139,'płot','fence')
INSERT INTO CARD VALUES (140,'podłoga','floor')
INSERT INTO CARD VALUES (141,'poduszka na kanapie','cushion')
INSERT INTO CARD VALUES (142,'poduszka w łóżku','pillow')
INSERT INTO CARD VALUES (143,'pokój dzienny','living room')
INSERT INTO CARD VALUES (144,'półka / regał','shelves')
INSERT INTO CARD VALUES (145,'prysznic','shower')
INSERT INTO CARD VALUES (146,'przedpokój','hall')
INSERT INTO CARD VALUES (147,'prześcieradło','sheet')
INSERT INTO CARD VALUES (148,'ręcznik','towel')
INSERT INTO CARD VALUES (149,'robot kuchenny','food processor')
INSERT INTO CARD VALUES (150,'roślina','plant')
INSERT INTO CARD VALUES (151,'schody','stairs')
INSERT INTO CARD VALUES (152,'ściana','wall')
INSERT INTO CARD VALUES (153,'sofa','sofa')
INSERT INTO CARD VALUES (154,'stół','table')
INSERT INTO CARD VALUES (155,'stolik nocny','bedside table')
INSERT INTO CARD VALUES (156,'strych','attic')
INSERT INTO CARD VALUES (157,'sufit','ceiling')
INSERT INTO CARD VALUES (158,'suszarka do włosów','hair dryer')
INSERT INTO CARD VALUES (159,'sypialnia','bedroom')
INSERT INTO CARD VALUES (160,'szafa','wardrobe')
INSERT INTO CARD VALUES (161,'szampon','shampoo')
INSERT INTO CARD VALUES (162,'szczoteczka od zębów','toothbrush')
INSERT INTO CARD VALUES (163,'szklanka','glass')
INSERT INTO CARD VALUES (164,'talerz','plate')
INSERT INTO CARD VALUES (165,'umywalka','washbasin')
INSERT INTO CARD VALUES (166,'odtwarzacz video,cd, dvd','player decoder')
INSERT INTO CARD VALUES (167,'wanna','bath')
INSERT INTO CARD VALUES (168,'toaleta','toilet')
INSERT INTO CARD VALUES (169,'widelec','fork')
INSERT INTO CARD VALUES (170,'wieża','stereo')
INSERT INTO CARD VALUES (171,'zamek w drzwiach','lock')
INSERT INTO CARD VALUES (172,'żelazko','iron')
INSERT INTO CARD VALUES (173,'zlew','sink')
INSERT INTO CARD VALUES (174,'zmywarka','dishwasher')
INSERT INTO CARD VALUES (175,'zwykły dywan','rug')