package com.learning.english.simple.db;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "CARD".
 */
public class Card {

    private Long id;
    /** Not-null value. */
    private String word;
    /** Not-null value. */
    private String definition;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Card() {
    }

    public Card(Long id) {
        this.id = id;
    }

    public Card(Long id, String word, String definition) {
        this.id = id;
        this.word = word;
        this.definition = definition;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getWord() {
        return word;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setWord(String word) {
        this.word = word;
    }

    /** Not-null value. */
    public String getDefinition() {
        return definition;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDefinition(String definition) {
        this.definition = definition;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
